flask_project_vl/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_project_vl/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_project_vl import db
from flask_project_vl.models import Post
from flask_project_vl.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html',
                           title='New post', form=form, legend='New post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update post',
                           form=form, legend='Update post')


@posts.route("/post/<int:post_id>/delete", methods=['POST', 'GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('You post has been deleted!', 'success')
    return redirect(url_for('posts.allpost'))

flask_project_vl/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_project_vl import db, bcrypt
from flask_project_vl.models import User, Post
from flask_project_vl.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, \
    ResetPasswordForm
from flask_project_vl.users.utils import save_picture
from flask_project_vl.users.utils import send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You can log in.', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Log in failed. Please chech your email and password', 'warning')
    return render_template('login.html', title='Log in', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts,
                           user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('The letter how to update password has been sent to your email with detailed instructions.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Reset password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('It is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.\
            generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!'
              'You can log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Resert password', form=form)

flask_project_vl/templates/account.html
{% extends "base.html" %}

{% block head %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .content-section{
      box-shadow: 10px 20px 8px darkslategray;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    a{
      color: #003049;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }
    
    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock head %}


{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Account</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   

{% endblock content %}

flask_project_vl/templates/allpost.html
{% extends "base.html" %}

{% block head %}
    <style>
        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }

        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        .card-title {
            margin-bottom: 0 !important;
            font-family: 'Bebas Neue', cursive;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

    </style>
{% endblock head %}

{% block content %}
    {% for post in posts.items %}
        <div class="container" style="display: flex;">
            <article class="media" style="display: flex; flex-direction: column;">
                <img class="rounded-circle article-img" style="margin-right: 5px;"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author"
                   style="margin: 0 auto;">{{ post.author.username }}</a>
            </article>

            <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h4 class="card-title"><a class="title"
                                              href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    </h4>

                    <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                    <br>
                    <br>
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-success mb-4"
                   href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flask_project_vl/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project_vl/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row align-items-end">
            <!-- Single Blog Area -->
            <div>
                <div class="single-blog-area clearfix mb-100">
                    <!-- Blog Content -->
                    <div class="single-blog-content">
                        <div class="line"></div>
                        <a href="#" class="post-tag">Lifestyle</a>
                        <h4><a href="#" class="post-headline" id="title-post">Welcome to this Lifestyle blog</a></h4>
                        <p class="post-text">Curabitur venenatis efficitur lorem sed tempor. Integer aliquet tempor cursus. Nullam
                            vestibulum convallis risus vel condimentum. Nullam auctor lorem in libero luctus, vel
                            volutpat quam tincidunt. Morbi sodales, dolor id ultricies dictum. Curabitur venenatis efficitur lorem sed tempor. Integer aliquet tempor cursus. Nullam
                            vestibulum convallis risus vel condimentum. Nullam auctor lorem in libero luctus, vel
                            volutpat quam tincidunt. Morbi sodales, dolor id ultricies dictum. Curabitur venenatis efficitur lorem sed tempor. Integer aliquet tempor cursus. Nullam
                            vestibulum convallis risus vel condimentum. Nullam auctor lorem in libero luctus, vel
                            volutpat quam tincidunt. Morbi sodales, dolor id ultricies dictum. Curabitur venenatis efficitur lorem sed tempor. Integer aliquet tempor cursus. Nullam
                            vestibulum convallis risus vel condimentum. Nullam auctor lorem in libero luctus, vel
                            volutpat quam tincidunt. Morbi sodales, dolor id ultricies dictum
                        </p>
                        <a href="#" class="btn original-btn">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flask_project_vl/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in</legend>

                <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}

            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Do you need account <a class="ml-2" href="{{ url_for('users.register') }}">Sing up</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_project_vl/templates/post.html
{% extends "base.html" %}

{% block head %}
    <style>
        .container {
            margin-bottom: 0.8rem;
        }

        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        .card-title {
            margin-bottom: 0 !important;
            font-family: 'Bebas Neue', cursive;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }
    </style>
{% endblock head %}

{% block content %}
    <div class="container" style="display: flex;">
        <article class="media" style="display: flex; flex-direction: column;">
            <img class="rounded-circle article-img" style="margin-right: 5px;"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
               style="margin: 0 auto">{{ post.author.username }}</a>
        </article>

        <div class="card" style="margin-bottom: 20px;">
            <div class="card-body">
                <h4 class="card-title">{{ post.title }}</h4>
                <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                <br>
                <br>
                <p class="card-text">{{ post.content }}</p>
            </div>
            <div class="card-footer" style="font-size: 20px;">
                {% if post.author == current_user %}
                    <div class="card-footer" style="font-size: 20px;"> {% if post.author == current_user %}
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        {#                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"#}
                        {#                                data-target="#deleteModal">Delete#}
                        {#                        </button>#}
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.delete_post', post_id=post.id) }}">Delete</a>
                        {#                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}"#}
                        {#                          method="POST">#}
                        {#                        <input class="btn btn-danger" type="submit" value="Delete">#}
                        {#                    </form>#}

                    {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    {#<!-- Modal -->#}
    {#    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">#}
    {#        <div class="modal-dialog" role="document">#}
    {#            <div class="modal-content">#}
    {#                <div class="modal-header">#}
    {#                    <h5 class="modal-title" id="deleteModalLabel">Do you really want delete this post?</h5>#}
    {#                    <button type="button" class="close" data-dismiss="modal"#}
    {#                            aria-label="Close">#}
    {#                        <span aria-hidden="true">&times;</span>#}
    {#                    </button>#}
    {#                </div>#}
    {#                <div class="modal-footer">#}
    {#                    <button type="button" class="btn btn-secondary"#}
    {#                            data-dismiss="modal">Close#}
    {#                    </button>#}
    {#                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}"#}
    {#                          method="POST">#}
    {#                        <input class="btn btn-danger" type="submit" value="Delete">#}
    {#                    </form>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    {##}
{% endblock content %}

flask_project_vl/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign up</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project_vl/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project_vl/templates/user_posts.html
{% extends "base.html" %}

{% block head %}
    <style>
        .container {
            margin-bottom: 0.8rem;
        }

        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        .card-title {
            margin-bottom: 0 !important;
            font-family: 'Bebas Neue', cursive;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }
    </style>
{% endblock head %}

{% block content %}
    <h1 class="mb-3">User's posts {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <div class="container" style="display: flex;">
            <article class="media" style="display: flex; flex-direction: column;">
                <img class="rounded-circle article-img" style="margin-right: 5px;"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                   style="margin: 0 auto">{{ post.author.username }}</a>
            </article>

            <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h4 class="card-title"><a class="title"
                                              href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    </h4>

                    <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                    <br>
                    <br>
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}


    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-success mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-success mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}